name: custom_open_mail_app
description: This library provides the ability to query the device for installed email apps and open those apps
version: 0.4.6
homepage: https://tikngroup.com
repository: https://github.com/maulanauls/open-mail-app-flutter

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  platform: ^3.1.0
  url_launcher: ^6.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.homex.open_mail_app
        pluginClass: OpenMailAppPlugin
      ios:
        pluginClass: OpenMailAppPlugin
